from google import genai
from fpdf import FPDF
import os
from datetime import datetime
from typing import Dict, Any, List

class ReportService:
    def __init__(self):
        api_key = os.getenv("GOOGLE_API_KEY")
        # Check for presence and avoid using the placeholder string from .env
        if api_key and "YOUR_GEMINI" not in api_key:
            self.client = genai.Client(api_key=api_key)
            print("Report Engine: Gemini AI Initialized (New SDK).")
        else:
            self.client = None
            print("Report Engine: Warning - GOOGLE_API_KEY missing or placeholder. LLM features disabled.")

    def generate_llm_report(self, structured_data: Dict[str, Any], conservation_plan: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Generates a comprehensive ecological report using LLM based on structured habitat data.
        Returns the report and metadata.
        """
        if not self.client:
            return {
                "report": "## Ecological Report Offline\nAI service is not configured.",
                "status": "Unknown"
            }
        
        # 1. Hybrid Rule-Based Classification (Still needed for factors, but status is hidden from text)
        frag = structured_data.get("fragmentation_index", 0.0)
        ndvi = structured_data.get("ndvi_index", 0.0)
        fire = structured_data.get("forest_fire_risk", "low")
        hdi = structured_data.get("hdi", 0.0)
        
        factors = []
        if frag > 0.7: factors.append("High Fragmentation")
        if ndvi < 0.6: factors.append("Vegetation Stress")
        if fire in ["medium", "high"]: factors.append("Fire Threat")
        if hdi > 0.7: factors.append("Human Interference")
        
        # Determine Status (Kept for internal logic/color but removed from display text as per user request)
        if len(factors) >= 3:
            status = "Critical Pressure"
            color = "#F44336"
        elif len(factors) >= 1:
            status = "Moderate Pressure"
            color = "#FF9800"
        else:
            status = "Stable Flow"
            color = "#4CAF50"

        species = structured_data.get("species")
        loc = structured_data.get("location")
        
        prompt = f"""
        Act as a Senior AI Conservation Assistant for WildSight.
        Generate a comprehensive, intelligent ecological report for: {species} at {loc}.
        
        [INPUT DATA]
        - Species: {species}
        - Location: {loc}
        - Temperature: {structured_data.get('temperature_avg')}C
        - Monsoon: {structured_data.get('monsoon_intensity')}
        - NDVI: {ndvi}
        - Fire Risk: {fire}
        - HDI: {hdi}
        - Fragmentation: {frag}
        - Bio-Type: {structured_data.get('geographical_type')}
        
        [DERIVED ANALYSIS]
        - Environmental Stressors: {", ".join(factors) if factors else "None Detected"}
        
        [REPORT STRUCTURE REQUIREMENTS]
        You MUST follow this exact 9-section structure:
        
        1. **COVER SECTION**: Species: {species}, Location: {loc}, Confidence: 95%. (DO NOT mention status here)
        2. **HABITAT OVERVIEW**: Short paragraph explaining the habitat metrics in **{loc}**.
        3. **RISK EXPLANATION**: (MOST IMPORTANT) Detailed analysis of environmental pressures on {species}. Link findings to data.
        4. **VISUAL ANALYTICS**: Mention that NDVI Heatmaps and Risk Radar Charts are provided in the dashboard.
        5. **AI INSIGHTS**: Generate 1-2 intelligent summary lines.
        6. **CONSERVATION MEASURES**: Dynamic solutions. Map pressures to specific solutions.
        7. **ACTION PRIORITY TABLE**: Generate a markdown table with columns: Factor | Severity | Priority.
        8. **FUTURE PREDICTION**: Predict habitat stability trend.
        9. **FOOTER**: "Generated by Wildsight AI" + Disclaimer.

        Keep it scientific and analytical. Avoid generic text.
        """
        
        try:
            print(f"Report Engine: Generating Deep Intelligence for {species} at {loc}...")
            response = self.client.models.generate_content(
                model='gemini-2.0-flash', 
                contents=prompt
            )
            return {
                "report": response.text,
                "status": status,
                "color": color,
                "factors": factors
            }
        except Exception as e:
            fallback = f"""
# WildSight Intelligence Report: {species}
**Location**: {loc}

## 2. Habitat Overview
The region of {loc} is characterized as a {structured_data.get('geographical_type')}. 
Key metrics: NDVI {ndvi}, Temp {structured_data.get('temperature_avg')}C.

## 3. Risk Explanation
Environmental pressures are primarily driven by: {", ".join(factors) if factors else "Minimal stressors detected"}. 

## 6. Conservation Measures
- **Reforestation**: Target NDVI hotspots.
- **Corridors**: Mitigate fragmentation of {frag}.
- **Surveillance**: Monitor {fire} risk zones.

## 7. Action Priority Table
| Factor | Severity | Priority |
|---|---|---|
| Fragmentation | {'High' if frag > 0.7 else 'Medium'} | {'Immediate' if frag > 0.7 else 'Moderate'} |

Generated by Wildsight AI
            """
            return {
                "report": fallback.strip(),
                "status": status,
                "color": color,
                "factors": factors
            }

    def generate_pdf_report(self, species_name: str, report_text: str, status_info: Dict[str, Any]) -> str:
        """
        Converts the markdown report into a Light-Themed professional PDF.
        """
        try:
            # Theme: Light Professional
            C_BG = (255, 255, 255)
            C_TEXT = (30, 41, 59)
            C_EMERALD = (5, 150, 105)
            C_SLATE = (100, 116, 139)
            
            pdf = FPDF()
            pdf.set_auto_page_break(auto=True, margin=15)
            pdf.add_page()
            
            # --- BACKGROUND ---
            pdf.set_fill_color(*C_BG)
            pdf.rect(0, 0, 210, 297, 'F')
            
            # --- HEADER ---
            pdf.set_text_color(*C_EMERALD)
            pdf.set_font("helvetica", "B", 24)
            pdf.set_y(15)
            pdf.cell(0, 15, "WILD SIGHT Intelligence Core", ln=True, align='L')
            
            pdf.set_font("helvetica", "B", 10)
            pdf.set_text_color(*C_SLATE)
            pdf.cell(0, 5, f"AI-GENERATED ECOLOGICAL AUDIT | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align='L')
            
            pdf.ln(15)
            
            # --- BODY ---
            pdf.set_text_color(*C_TEXT)
            lines = report_text.split('\n')
            
            for line in lines:
                line = line.strip()
                if not line:
                    pdf.ln(4)
                    continue
                
                # HEADERS
                if line.startswith('#'):
                    clean_line = line.replace('#', '').strip()
                    pdf.set_font("helvetica", "B", 16)
                    pdf.set_text_color(*C_EMERALD)
                    pdf.ln(6)
                    pdf.cell(0, 10, clean_line, ln=True)
                    # Accent Line
                    y = pdf.get_y()
                    pdf.set_draw_color(*C_EMERALD)
                    pdf.set_line_width(0.5)
                    pdf.line(10, y, 60, y)
                    pdf.ln(4)
                    pdf.set_text_color(*C_TEXT)
                    
                # TABLE HANDLING (Markdown tables)
                elif '|' in line and not any(c in line for c in [':', '---']):
                    pdf.set_font("helvetica", "B", 9)
                    parts = [p.strip() for p in line.split('|') if p.strip()]
                    if not parts: continue
                    
                    col_width = (pdf.w - 30) / len(parts)
                    for part in parts:
                        pdf.set_fill_color(248, 250, 252)
                        pdf.set_draw_color(226, 232, 240)
                        pdf.cell(col_width, 10, part, border=1, fill=True)
                    pdf.ln()

                # BULLETS
                elif line.startswith('-') or line.startswith('*'):
                    clean_line = line.replace('-', '').replace('*', '').strip()
                    safe_line = "".join(c if ord(c) < 256 else "?" for c in clean_line)
                    pdf.set_font("helvetica", "", 11)
                    pdf.set_x(15)
                    pdf.multi_cell(0, 8, txt=f"> {safe_line}")
                
                # NORMAL TEXT
                elif not line.startswith('|') and not line.startswith('---'):
                    clean_line = line.replace('**', '').replace('___', '').replace('__', '')
                    pdf.set_font("helvetica", "", 11)
                    pdf.set_x(10)
                    try:
                        pdf.multi_cell(0, 7, txt=clean_line.encode('latin-1', 'replace').decode('latin-1'))
                    except Exception:
                        pdf.multi_cell(0, 7, txt="[Internal Data Fragment]")
            
            # --- FOOTER ---
            pdf.set_y(-20)
            pdf.set_font("helvetica", "I", 9)
            pdf.set_text_color(*C_SLATE)
            pdf.cell(0, 10, "Generated by Wildsight AI | (c) 2026 Republic of India", 0, 0, 'C')

            reports_dir = os.path.abspath(os.path.join(os.getcwd(), "exports", "reports"))
            os.makedirs(reports_dir, exist_ok=True)
            
            filename = f"WildSight_Audit_{species_name.replace(' ', '_')}.pdf"
            output_path = os.path.join(reports_dir, filename)
            pdf.output(output_path)
            return output_path
            
        except Exception as e:
            print(f"PDF ERROR: {e}")
            import traceback
            traceback.print_exc()
            return None
            
            # --- FOOTER ---
            pdf.set_y(-20)
            pdf.set_font("helvetica", "I", 9)
            pdf.set_text_color(*C_SLATE)
            pdf.cell(0, 10, "Generated by Wildsight AI | (c) 2026 Republic of India", 0, 0, 'C')

            reports_dir = os.path.abspath(os.path.join(os.getcwd(), "exports", "reports"))
            os.makedirs(reports_dir, exist_ok=True)
            
            filename = f"WildSight_Audit_{species_name.replace(' ', '_')}.pdf"
            output_path = os.path.join(reports_dir, filename)
            pdf.output(output_path)
            return output_path
            
        except Exception as e:
            print(f"PDF ERROR: {e}")
            import traceback
            traceback.print_exc()
            return None

report_service = ReportService()
